// Code generated by merging. DO NOT EDIT.
package sszgen

import "github.com/karalabe/ssz"

// SizeSSZ returns the total size of the static ssz object.
func (obj *FixedTestStruct) SizeSSZ(sizer *ssz.Sizer) uint32 {
	return 1 + 8 + 4
}

// DefineSSZ defines how an object is encoded/decoded.
func (obj *FixedTestStruct) DefineSSZ(codec *ssz.Codec) {
	ssz.DefineUint8(codec, &obj.A)  // Field  (0) - A - 1 bytes
	ssz.DefineUint64(codec, &obj.B) // Field  (1) - B - 8 bytes
	ssz.DefineUint32(codec, &obj.C) // Field  (2) - C - 4 bytes
}

// ClearSSZ zeroes out all fields of FixedTestStruct for leftover decode.
func (obj *FixedTestStruct) ClearSSZ() {
	obj.A = 0
	obj.B = 0
	obj.C = 0
}
