// Code generated by merging. DO NOT EDIT.
package sszgen

import "github.com/karalabe/ssz"

// SizeSSZ returns the total size of the static ssz object.
func (obj *SmallTestStruct) SizeSSZ(sizer *ssz.Sizer) uint32 {
	return 2 + 2
}

// DefineSSZ defines how an object is encoded/decoded.
func (obj *SmallTestStruct) DefineSSZ(codec *ssz.Codec) {
	ssz.DefineUint16(codec, &obj.A) // Field  (0) - A - 2 bytes
	ssz.DefineUint16(codec, &obj.B) // Field  (1) - B - 2 bytes
}

// ClearSSZ zeroes out all fields of SmallTestStruct for leftover decode.
func (obj *SmallTestStruct) ClearSSZ() {
	obj.A = 0
	obj.B = 0
}
