// Code generated by merging. DO NOT EDIT.
package sszgen

import "github.com/karalabe/ssz"

// Cached static size computed on package init.
var staticSizeCacheProposerSlashing = ssz.PrecomputeStaticSizeCache((*ProposerSlashing)(nil))

// SizeSSZ returns the total size of the static ssz object.
func (obj *ProposerSlashing) SizeSSZ(sizer *ssz.Sizer) (size uint32) {
	if fork := int(sizer.Fork()); fork < len(staticSizeCacheProposerSlashing) {
		return staticSizeCacheProposerSlashing[fork]
	}
	size = (*SignedBeaconBlockHeader)(nil).SizeSSZ(sizer) + (*SignedBeaconBlockHeader)(nil).SizeSSZ(sizer)
	return size
}

// DefineSSZ defines how an object is encoded/decoded.
func (obj *ProposerSlashing) DefineSSZ(codec *ssz.Codec) {
	ssz.DefineStaticObject(codec, &obj.Header1) // Field  (0) - Header1 - ? bytes (SignedBeaconBlockHeader)
	ssz.DefineStaticObject(codec, &obj.Header2) // Field  (1) - Header2 - ? bytes (SignedBeaconBlockHeader)
}

// ClearSSZ zeroes out all fields of ProposerSlashing for leftover decode.
func (obj *ProposerSlashing) ClearSSZ() {
	if obj.Header1 != nil {
		obj.Header1.ClearSSZ()
	}
	if obj.Header2 != nil {
		obj.Header2.ClearSSZ()
	}
}
