// Code generated by merging. DO NOT EDIT.
package sszgen

import "github.com/karalabe/ssz"

// SizeSSZ returns the total size of the static ssz object.
func (obj *DepositMessage) SizeSSZ(sizer *ssz.Sizer) uint32 {
	return 48 + 32 + 8
}

// DefineSSZ defines how an object is encoded/decoded.
func (obj *DepositMessage) DefineSSZ(codec *ssz.Codec) {
	ssz.DefineStaticBytes(codec, &obj.Pubkey)                // Field  (0) -                Pubkey - 48 bytes
	ssz.DefineStaticBytes(codec, &obj.WithdrawalCredentials) // Field  (1) - WithdrawalCredentials - 32 bytes
	ssz.DefineUint64(codec, &obj.Amount)                     // Field  (2) -                Amount -  8 bytes
}

// ClearSSZ zeroes out all fields of DepositMessage for leftover decode.
func (obj *DepositMessage) ClearSSZ() {
	obj.Pubkey = [48]byte{}
	obj.WithdrawalCredentials = [32]byte{}
	obj.Amount = 0
}
