// Code generated by merging. DO NOT EDIT.
package sszgen

import "github.com/karalabe/ssz"

// SizeSSZ returns the total size of the static ssz object.
func (obj *SingleFieldTestStructMonolith) SizeSSZ(sizer *ssz.Sizer) (size uint32) {
	if sizer.Fork() >= ssz.ForkUnknown {
		size += 1
	}
	return size
}

// DefineSSZ defines how an object is encoded/decoded.
func (obj *SingleFieldTestStructMonolith) DefineSSZ(codec *ssz.Codec) {
	ssz.DefineUint8PointerOnFork(codec, &obj.A, ssz.ForkFilter{Added: ssz.ForkUnknown}) // Field  (0) - A - 1 bytes
}

// ClearSSZ zeroes out all fields of SingleFieldTestStructMonolith for leftover decode.
func (obj *SingleFieldTestStructMonolith) ClearSSZ() {
	obj.A = nil
}
