// Code generated by merging. DO NOT EDIT.
package sszgen

import "github.com/karalabe/ssz"

// SizeSSZ returns the total size of the static ssz object.
func (obj *WithdrawalVariation) SizeSSZ(sizer *ssz.Sizer) uint32 {
	return 8 + 8 + 20 + 8
}

// DefineSSZ defines how an object is encoded/decoded.
func (obj *WithdrawalVariation) DefineSSZ(codec *ssz.Codec) {
	ssz.DefineUint64(codec, &obj.Index)                   // Field  (0) -     Index -  8 bytes
	ssz.DefineUint64(codec, &obj.Validator)               // Field  (1) - Validator -  8 bytes
	ssz.DefineCheckedStaticBytes(codec, &obj.Address, 20) // Field  (2) -   Address - 20 bytes
	ssz.DefineUint64(codec, &obj.Amount)                  // Field  (3) -    Amount -  8 bytes
}

// ClearSSZ zeroes out all fields of WithdrawalVariation for leftover decode.
func (obj *WithdrawalVariation) ClearSSZ() {
	obj.Index = 0
	obj.Validator = 0
	obj.Address = obj.Address[:0]
	obj.Amount = 0
}
