// Code generated by merging. DO NOT EDIT.
package sszgen

import "github.com/karalabe/ssz"

// SizeSSZ returns the total size of the static ssz object.
func (obj *SyncAggregate) SizeSSZ(sizer *ssz.Sizer) uint32 {
	return 64 + 96
}

// DefineSSZ defines how an object is encoded/decoded.
func (obj *SyncAggregate) DefineSSZ(codec *ssz.Codec) {
	ssz.DefineStaticBytes(codec, &obj.SyncCommiteeBits)      // Field  (0) -      SyncCommiteeBits - 64 bytes
	ssz.DefineStaticBytes(codec, &obj.SyncCommiteeSignature) // Field  (1) - SyncCommiteeSignature - 96 bytes
}

// ClearSSZ zeroes out all fields of SyncAggregate for leftover decode.
func (obj *SyncAggregate) ClearSSZ() {
	obj.SyncCommiteeBits = [64]byte{}
	obj.SyncCommiteeSignature = [96]byte{}
}
