// Code generated by merging. DO NOT EDIT.
package sszgen

import "github.com/karalabe/ssz"

// Cached static size computed on package init.
var staticSizeCacheSignedBeaconBlockHeader = ssz.PrecomputeStaticSizeCache((*SignedBeaconBlockHeader)(nil))

// SizeSSZ returns the total size of the static ssz object.
func (obj *SignedBeaconBlockHeader) SizeSSZ(sizer *ssz.Sizer) (size uint32) {
	if fork := int(sizer.Fork()); fork < len(staticSizeCacheSignedBeaconBlockHeader) {
		return staticSizeCacheSignedBeaconBlockHeader[fork]
	}
	size = (*BeaconBlockHeader)(nil).SizeSSZ(sizer) + 96
	return size
}

// DefineSSZ defines how an object is encoded/decoded.
func (obj *SignedBeaconBlockHeader) DefineSSZ(codec *ssz.Codec) {
	ssz.DefineStaticObject(codec, &obj.Header)   // Field  (0) -    Header -  ? bytes (BeaconBlockHeader)
	ssz.DefineStaticBytes(codec, &obj.Signature) // Field  (1) - Signature - 96 bytes
}

// ClearSSZ zeroes out all fields of SignedBeaconBlockHeader for leftover decode.
func (obj *SignedBeaconBlockHeader) ClearSSZ() {
	if obj.Header != nil {
		obj.Header.ClearSSZ()
	}
	obj.Signature = [96]byte{}
}
