// Code generated by merging. DO NOT EDIT.
package sszgen

import "github.com/karalabe/ssz"

// SizeSSZ returns the total size of the static ssz object.
func (obj *Eth1Data) SizeSSZ(sizer *ssz.Sizer) uint32 {
	return 32 + 8 + 32
}

// DefineSSZ defines how an object is encoded/decoded.
func (obj *Eth1Data) DefineSSZ(codec *ssz.Codec) {
	ssz.DefineStaticBytes(codec, &obj.DepositRoot) // Field  (0) -  DepositRoot - 32 bytes
	ssz.DefineUint64(codec, &obj.DepositCount)     // Field  (1) - DepositCount -  8 bytes
	ssz.DefineStaticBytes(codec, &obj.BlockHash)   // Field  (2) -    BlockHash - 32 bytes
}

// ClearSSZ zeroes out all fields of Eth1Data for leftover decode.
func (obj *Eth1Data) ClearSSZ() {
	obj.DepositRoot = [32]byte{}
	obj.DepositCount = 0
	obj.BlockHash = [32]byte{}
}
