// Code generated by merging. DO NOT EDIT.
package sszgen

import "github.com/karalabe/ssz"

// SizeSSZ returns the total size of the static ssz object.
func (obj *SyncCommittee) SizeSSZ(sizer *ssz.Sizer) uint32 {
	return 512*48 + 48
}

// DefineSSZ defines how an object is encoded/decoded.
func (obj *SyncCommittee) DefineSSZ(codec *ssz.Codec) {
	ssz.DefineUnsafeArrayOfStaticBytes(codec, obj.PubKeys[:]) // Field  (0) -         PubKeys - 24576 bytes
	ssz.DefineStaticBytes(codec, &obj.AggregatePubKey)        // Field  (1) - AggregatePubKey -    48 bytes
}

// ClearSSZ zeroes out all fields of SyncCommittee for leftover decode.
func (obj *SyncCommittee) ClearSSZ() {
	obj.PubKeys = [512][48]byte{}
	obj.AggregatePubKey = [48]byte{}
}
