// Code generated by merging. DO NOT EDIT.
package sszgen

import "github.com/karalabe/ssz"

// SizeSSZ returns the total size of the static ssz object.
func (obj *BLSToExecutionChange) SizeSSZ(sizer *ssz.Sizer) uint32 {
	return 8 + 48 + 20
}

// DefineSSZ defines how an object is encoded/decoded.
func (obj *BLSToExecutionChange) DefineSSZ(codec *ssz.Codec) {
	ssz.DefineUint64(codec, &obj.ValidatorIndex)          // Field  (0) -     ValidatorIndex -  8 bytes
	ssz.DefineStaticBytes(codec, &obj.FromBLSPubKey)      // Field  (1) -      FromBLSPubKey - 48 bytes
	ssz.DefineStaticBytes(codec, &obj.ToExecutionAddress) // Field  (2) - ToExecutionAddress - 20 bytes
}

// ClearSSZ zeroes out all fields of BLSToExecutionChange for leftover decode.
func (obj *BLSToExecutionChange) ClearSSZ() {
	obj.ValidatorIndex = 0
	obj.FromBLSPubKey = [48]byte{}
	obj.ToExecutionAddress = [20]byte{}
}
