// Code generated by merging. DO NOT EDIT.
package sszgen

import "github.com/karalabe/ssz"

// SizeSSZ returns the total size of the static ssz object.
func (obj *HistoricalBatchVariation) SizeSSZ(sizer *ssz.Sizer) uint32 {
	return 8192*32 + 8192*32
}

// DefineSSZ defines how an object is encoded/decoded.
func (obj *HistoricalBatchVariation) DefineSSZ(codec *ssz.Codec) {
	ssz.DefineUnsafeArrayOfStaticBytes(codec, obj.BlockRoots[:])      // Field  (0) - BlockRoots - 262144 bytes
	ssz.DefineCheckedArrayOfStaticBytes(codec, &obj.StateRoots, 8192) // Field  (1) - StateRoots - 262144 bytes
}

// ClearSSZ zeroes out all fields of HistoricalBatchVariation for leftover decode.
func (obj *HistoricalBatchVariation) ClearSSZ() {
	obj.BlockRoots = [8192]Hash{}
	obj.StateRoots = obj.StateRoots[:0]
}
