// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package consensus_spec_tests

// ClearSSZ zeroes out all fields of SmallTestStructMonolith for leftover decode.
func (obj *SmallTestStructMonolith) ClearSSZ() {
	obj.A = nil
	obj.B = 0
}
