// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package consensus_spec_tests

// ClearSSZ zeroes out all fields of SyncAggregate for leftover decode.
func (obj *SyncAggregate) ClearSSZ() {
	obj.SyncCommiteeBits = [64]byte{}
	obj.SyncCommiteeSignature = [96]byte{}
}
