// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package consensus_spec_tests

// ClearSSZ zeroes out all fields of Eth1Data for leftover decode.
func (obj *Eth1Data) ClearSSZ() {
	obj.DepositRoot = [32]byte{}
	obj.DepositCount = 0
	obj.BlockHash = [32]byte{}
}
