// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package consensus_spec_tests

// ClearSSZ zeroes out all fields of SyncCommittee for leftover decode.
func (obj *SyncCommittee) ClearSSZ() {
	obj.PubKeys = [512][48]byte{}
	obj.AggregatePubKey = [48]byte{}
}
