// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package consensus_spec_tests

// ClearSSZ zeroes out all fields of SingleFieldTestStructMonolith for leftover decode.
func (obj *SingleFieldTestStructMonolith) ClearSSZ() {
	obj.A = nil
}
