// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package consensus_spec_tests

// ClearSSZ zeroes out all fields of HistoricalBatchVariation for leftover decode.
func (obj *HistoricalBatchVariation) ClearSSZ() {
	obj.BlockRoots = [8192]Hash{}
	obj.StateRoots = obj.StateRoots[:0]
}
