// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package consensus_spec_tests

// ClearSSZ zeroes out all fields of AttestationData for leftover decode.
func (obj *AttestationData) ClearSSZ() {
	obj.Slot = 0
	obj.Index = 0
	obj.BeaconBlockHash = [32]byte{}
	if obj.Source != nil {
		obj.Source.ClearSSZ()
	}
	if obj.Target != nil {
		obj.Target.ClearSSZ()
	}
}
