// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package consensus_spec_tests

// ClearSSZ zeroes out all fields of Deposit for leftover decode.
func (obj *Deposit) ClearSSZ() {
	obj.Proof = [33][32]byte{}
	if obj.Data != nil {
		obj.Data.ClearSSZ()
	}
}
