// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package consensus_spec_tests

// ClearSSZ zeroes out all fields of BeaconBlockHeader for leftover decode.
func (obj *BeaconBlockHeader) ClearSSZ() {
	obj.Slot = 0
	obj.ProposerIndex = 0
	obj.ParentRoot = [32]byte{}
	obj.StateRoot = [32]byte{}
	obj.BodyRoot = [32]byte{}
}
