// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package consensus_spec_tests

// ClearSSZ zeroes out all fields of HistoricalSummary for leftover decode.
func (obj *HistoricalSummary) ClearSSZ() {
	obj.BlockSummaryRoot = [32]byte{}
	obj.StateSummaryRoot = [32]byte{}
}
