// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package consensus_spec_tests

// ClearSSZ zeroes out all fields of Checkpoint for leftover decode.
func (obj *Checkpoint) ClearSSZ() {
	obj.Epoch = 0
	obj.Root = [32]byte{}
}
