// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package consensus_spec_tests

// ClearSSZ zeroes out all fields of SignedVoluntaryExit for leftover decode.
func (obj *SignedVoluntaryExit) ClearSSZ() {
	if obj.Exit != nil {
		obj.Exit.ClearSSZ()
	}
	obj.Signature = [96]byte{}
}
