// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package sszgen

// ClearSSZ zeroes out all fields of AttesterSlashing for leftover decode.
func (obj *AttesterSlashing) ClearSSZ() {
	if obj.Attestation1 != nil {
		obj.Attestation1.ClearSSZ()
	}
	if obj.Attestation2 != nil {
		obj.Attestation2.ClearSSZ()
	}
}
