// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package sszgen

// ClearSSZ zeroes out all fields of FixedTestStructMonolith for leftover decode.
func (obj *FixedTestStructMonolith) ClearSSZ() {
	obj.A = nil
	obj.B = nil
	obj.C = nil
}
