// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package sszgen

// ClearSSZ zeroes out all fields of BeaconStateAltair for leftover decode.
func (obj *BeaconStateAltair) ClearSSZ() {
	obj.GenesisTime = 0
	obj.GenesisValidatorsRoot = obj.GenesisValidatorsRoot[:0]
	obj.Slot = 0
	if obj.Fork != nil {
		obj.Fork.ClearSSZ()
	}
	if obj.LatestBlockHeader != nil {
		obj.LatestBlockHeader.ClearSSZ()
	}
	obj.BlockRoots = [8192][32]byte{}
	obj.StateRoots = [8192][32]byte{}
	obj.HistoricalRoots = nil
	if obj.Eth1Data != nil {
		obj.Eth1Data.ClearSSZ()
	}
	obj.Eth1DataVotes = nil
	obj.Eth1DepositIndex = 0
	obj.Validators = nil
	obj.Balances = nil
	obj.RandaoMixes = [65536][32]byte{}
	obj.Slashings = [8192]uint64{}
	obj.PreviousEpochParticipation = nil
	obj.CurrentEpochParticipation = nil
	obj.JustificationBits = [1]byte{}
	if obj.PreviousJustifiedCheckpoint != nil {
		obj.PreviousJustifiedCheckpoint.ClearSSZ()
	}
	if obj.CurrentJustifiedCheckpoint != nil {
		obj.CurrentJustifiedCheckpoint.ClearSSZ()
	}
	if obj.FinalizedCheckpoint != nil {
		obj.FinalizedCheckpoint.ClearSSZ()
	}
	obj.InactivityScores = nil
	if obj.CurrentSyncCommittee != nil {
		obj.CurrentSyncCommittee.ClearSSZ()
	}
	if obj.NextSyncCommittee != nil {
		obj.NextSyncCommittee.ClearSSZ()
	}
}
