// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package sszgen

// ClearSSZ zeroes out all fields of SignedBeaconBlockHeader for leftover decode.
func (obj *SignedBeaconBlockHeader) ClearSSZ() {
	if obj.Header != nil {
		obj.Header.ClearSSZ()
	}
	obj.Signature = [96]byte{}
}
