// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package sszgen

// ClearSSZ zeroes out all fields of AttestationVariation2 for leftover decode.
func (obj *AttestationVariation2) ClearSSZ() {
	obj.AggregationBits = nil
	if obj.Data != nil {
		obj.Data.ClearSSZ()
	}
	obj.Future = nil
	obj.Signature = [96]byte{}
}
