// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package sszgen

// ClearSSZ zeroes out all fields of ValidatorMonolith for leftover decode.
func (obj *ValidatorMonolith) ClearSSZ() {
	obj.Pubkey = [48]byte{}
	obj.WithdrawalCredentials = [32]byte{}
	obj.EffectiveBalance = 0
	obj.Slashed = nil
	obj.ActivationEligibilityEpoch = 0
	obj.ActivationEpoch = 0
	obj.ExitEpoch = 0
	obj.WithdrawableEpoch = 0
}
