// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package sszgen

// ClearSSZ zeroes out all fields of BLSToExecutionChange for leftover decode.
func (obj *BLSToExecutionChange) ClearSSZ() {
	obj.ValidatorIndex = 0
	obj.FromBLSPubKey = [48]byte{}
	obj.ToExecutionAddress = [20]byte{}
}
