// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package sszgen

// ClearSSZ zeroes out all fields of AttestationDataVariation3 for leftover decode.
func (obj *AttestationDataVariation3) ClearSSZ() {
	obj.Slot = 0
	obj.Index = 0
	obj.BeaconBlockHash = [32]byte{}
	if obj.Source != nil {
		obj.Source.ClearSSZ()
	}
	if obj.Target != nil {
		obj.Target.ClearSSZ()
	}
	obj.Future = nil
}
