// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package sszgen

// ClearSSZ zeroes out all fields of SingleFieldTestStruct for leftover decode.
func (obj *SingleFieldTestStruct) ClearSSZ() {
	obj.A = 0
}
