// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package sszgen

// ClearSSZ zeroes out all fields of BeaconBlock for leftover decode.
func (obj *BeaconBlock) ClearSSZ() {
	obj.Slot = 0
	obj.ProposerIndex = 0
	obj.ParentRoot = [32]byte{}
	obj.StateRoot = [32]byte{}
	if obj.Body != nil {
		obj.Body.ClearSSZ()
	}
}
