// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package sszgen

// ClearSSZ zeroes out all fields of DepositMessage for leftover decode.
func (obj *DepositMessage) ClearSSZ() {
	obj.Pubkey = [48]byte{}
	obj.WithdrawalCredentials = [32]byte{}
	obj.Amount = 0
}
