// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package sszgen

// ClearSSZ zeroes out all fields of HistoricalBatch for leftover decode.
func (obj *HistoricalBatch) ClearSSZ() {
	obj.BlockRoots = [8192]Hash{}
	obj.StateRoots = [8192]Hash{}
}
