// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package sszgen

// ClearSSZ zeroes out all fields of BeaconBlockBody for leftover decode.
func (obj *BeaconBlockBody) ClearSSZ() {
	obj.RandaoReveal = [96]byte{}
	if obj.Eth1Data != nil {
		obj.Eth1Data.ClearSSZ()
	}
	obj.Graffiti = [32]byte{}
	obj.ProposerSlashings = nil
	obj.AttesterSlashings = nil
	obj.Attestations = nil
	obj.Deposits = nil
	obj.VoluntaryExits = nil
}
