// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package sszgen

// ClearSSZ zeroes out all fields of ProposerSlashing for leftover decode.
func (obj *ProposerSlashing) ClearSSZ() {
	if obj.Header1 != nil {
		obj.Header1.ClearSSZ()
	}
	if obj.Header2 != nil {
		obj.Header2.ClearSSZ()
	}
}
