// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package gen_clear_ssz

// ClearSSZ zeroes out all fields of AttestationVariation1 for leftover decode.
func (obj *AttestationVariation1) ClearSSZ() {
	obj.Future = nil
	obj.AggregationBits = nil
	if obj.Data != nil {
		obj.Data.ClearSSZ()
	}
	obj.Signature = [96]byte{}
}
