// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package gen_clear_ssz

// ClearSSZ zeroes out all fields of BitsStructMonolith for leftover decode.
func (obj *BitsStructMonolith) ClearSSZ() {
	obj.A = nil
	obj.B = nil
	obj.C = [1]byte{}
	obj.D = nil
	obj.E = [1]byte{}
}
