// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package gen_clear_ssz

// ClearSSZ zeroes out all fields of Validator for leftover decode.
func (obj *Validator) ClearSSZ() {
	obj.Pubkey = [48]byte{}
	obj.WithdrawalCredentials = [32]byte{}
	obj.EffectiveBalance = 0
	obj.Slashed = false
	obj.ActivationEligibilityEpoch = 0
	obj.ActivationEpoch = 0
	obj.ExitEpoch = 0
	obj.WithdrawableEpoch = 0
}
