// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package gen_clear_ssz

// ClearSSZ zeroes out all fields of SignedBLSToExecutionChange for leftover decode.
func (obj *SignedBLSToExecutionChange) ClearSSZ() {
	if obj.Message != nil {
		obj.Message.ClearSSZ()
	}
	obj.Signature = [96]byte{}
}
