// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package gen_clear_ssz

// ClearSSZ zeroes out all fields of DepositData for leftover decode.
func (obj *DepositData) ClearSSZ() {
	obj.Pubkey = [48]byte{}
	obj.WithdrawalCredentials = [32]byte{}
	obj.Amount = 0
	obj.Signature = [96]byte{}
}
