// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package gen_clear_ssz

// ClearSSZ zeroes out all fields of AggregateAndProof for leftover decode.
func (obj *AggregateAndProof) ClearSSZ() {
	obj.Index = 0
	if obj.Aggregate != nil {
		obj.Aggregate.ClearSSZ()
	}
	obj.SelectionProof = [96]byte{}
}
