// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package gen_clear_ssz

// ClearSSZ zeroes out all fields of PendingAttestation for leftover decode.
func (obj *PendingAttestation) ClearSSZ() {
	obj.AggregationBits = nil
	if obj.Data != nil {
		obj.Data.ClearSSZ()
	}
	obj.InclusionDelay = 0
	obj.ProposerIndex = 0
}
