// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package gen_clear_ssz

// ClearSSZ zeroes out all fields of SmallTestStruct for leftover decode.
func (obj *SmallTestStruct) ClearSSZ() {
	obj.A = 0
	obj.B = 0
}
