// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package gen_clear_ssz

// ClearSSZ zeroes out all fields of Eth1Block for leftover decode.
func (obj *Eth1Block) ClearSSZ() {
	obj.Timestamp = 0
	obj.DepositRoot = [32]byte{}
	obj.DepositCount = 0
}
